### ISSUE TITLE
Can't connect to: https://supfam.mrc-lmb.cam.ac.uk/GenomePrep/

### ISSUE THREAD

**Issue by opain** [changlubio/GenomePrep#4]
Hello,

Thanks for developing this great tool!

I am unable to connect to your server: https://supfam.mrc-lmb.cam.ac.uk/GenomePrep/
I also can't connect when trying to download some of the software dependencies, such as: https://supfam.mrc-lmb.cam.ac.uk/GenomePrep/datadir/api.23andme.com

Thanks in advance for your advice.

**Comment by changlubio** [comment]
Hi Oliver,

Thanks for your message and sorry that the server is not working. Unfortunately, it’s currently out of my hands to get it back on. I’m going to upload the datadir files into Zenodo.

Best wishes
Chang

From: Oliver Pain ***@***.***>
Date: Wednesday, 29 May 2024 at 12:00
To: changlubio/GenomePrep ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [changlubio/GenomePrep] Can't connect to: https://supfam.mrc-lmb.cam.ac.uk/GenomePrep/ (Issue #4)

Hello,

Thanks for developing this great tool!

I am unable to connect to your server: https://supfam.mrc-lmb.cam.ac.uk/GenomePrep/
I also can't connect when trying to download some of the software dependencies, such as: https://supfam.mrc-lmb.cam.ac.uk/GenomePrep/datadir/api.23andme.com

Thanks in advance for your advice.

**Comment by changlubio** [comment]
Hi, The dependencies are uploaded to Zenodo and links updated in the ReadMe file.
